<?php

return [
    'kecamatan' => [
        'Bakung' => [
            'Desa Bakung',
            'Desa Bululawang',
            'Desa Kedungbanteng',
            'Desa Lorejo',
            'Desa Ngrejo',
            'Desa Plandirejo',
            'Desa Pulerejo',
            'Desa Sidomulyo',
            'Desa Sumberdadi',
            'Desa Tumpakkepuh',
            'Desa Tumpakoyot',
        ],
        'Binangun' => [
            'Desa Binangun',
            'Desa Birowo',
            'Desa Kedungwungu',
            'Desa Ngadri',
            'Desa Ngembul',
            'Desa Rejoso',
            'Desa Salamrejo',
            'Desa Sambigede',
            'Desa Sukorame',
            'Desa Sumberkembar',
            'Desa Tawangrejo',
            'Desa Umbuldamar',
        ],
        'Doko' => [
            'Desa Doko',
            'Desa Genengan',
            'Desa Jambepawon',
            'Desa Kalimanis',
            'Desa Plumbangan',
            'Desa Resapombo',
            'Desa Sidorejo',
            'Desa Slorok',
            'Desa Sumberurip',
            'Desa Suru',
        ],
        'Gandusari' => [
            'Desa Butun',
            'Desa Gadungan',
            'Desa Gandusari',
            'Desa Gondang',
            'Desa Kotes',
            'Desa Krisik',
            'Desa Ngaringan',
            'Desa Semen',
            'Desa Slumbung',
            'Desa Soso',
            'Desa Sukosewu',
            'Desa Sumberagung',
            'Desa Tambakan',
            'Desa Tulungrejo',
        ],
        'Garum' => [
            'Desa Karangrejo',
            'Desa Pojok',
            'Desa Sidodadi',
            'Desa Slorok',
            'Desa Tingal',
            'Kelurahan Bence',
            'Kelurahan Garum',
            'Kelurahan Sumberdiren',
            'Kelurahan Tawangsari',
        ],
        'Kademangan' => [
            'Desa Bendosari',
            'Desa Darungan',
            'Desa Dawuhan',
            'Desa Jimbe',
            'Desa Kebonsari',
            'Desa Maron',
            'Desa Pakisaji',
            'Desa Panggungduwet',
            'Desa Plosorejo',
            'Desa Plumpungrejo',
            'Desa Rejowinangun',
            'Desa Sumberjati',
            'Desa Sumberjo',
            'Desa Suruhwadang',
            'Kelurahan Kademangan',
        ],
        'Kanigoro' => [
            'Desa Banggle',
            'Desa Gaprang',
            'Desa Gogodeso',
            'Desa Jatinom',
            'Desa Karangsono',
            'Desa Kuningan',
            'Desa Minggirsari',
            'Desa Papungan',
            'Desa Sawentar',
            'Desa Tlogo',
            'Kelurahan Kanigoro',
            'Kelurahan Satreyan',
        ],
        'Kesamben' => [
            'Desa Bumirejo',
            'Desa Jugo',
            'Desa Kemirigede',
            'Desa Kesamben',
            'Desa Pagergunung',
            'Desa Pagerwojo',
            'Desa Siraman',
            'Desa Sukoanyar',
            'Desa Tapakrejo',
            'Desa Tepas',
        ],
        'Nglegok' => [
            'Desa Bangsri',
            'Desa Dayu',
            'Desa Jiwut',
            'Desa Kedawung',
            'Desa Kemloko',
            'Desa Krenceng',
            'Desa Modangan',
            'Desa Ngoran',
            'Desa Penataran',
            'Desa Sumberasri',
            'Kelurahan Nglegok',
        ],
        'Panggungrejo' => [
            'Desa Balerejo',
            'Desa Bumiayu',
            'Desa Kaligambir',
            'Desa Kalitengah',
            'Desa Margomulyo',
            'Desa Panggungasri',
            'Desa Panggungrejo',
            'Desa Serang',
            'Desa Sumberagung',
            'Desa Sumbersih',
        ],
        'Ponggok' => [
            'Desa Bacem',
            'Desa Bendo',
            'Desa Candirejo',
            'Desa Dadaplangu',
            'Desa Gembongan',
            'Desa Jatilengger',
            'Desa Karangbendo',
            'Desa Kawedusan',
            'Desa Kebonduren',
            'Desa Langon',
            'Desa Maliran',
            'Desa Pojok',
            'Desa Ponggok',
            'Desa Ringinanyar',
            'Desa Sidorejo',
        ],
        'Sanankulon' => [
            'Desa Bendosari',
            'Desa Bendowulung',
            'Desa Gledug',
            'Desa Jeding',
            'Desa Kalipucung',
            'Desa Plosoarang',
            'Desa Purworejo',
            'Desa Sanankulon',
            'Desa Sumber',
            'Desa Sumberingin',
            'Desa Sumberjo',
            'Desa Tuliskriyo',
        ],
        'Selorejo' => [
            'Desa Ampelgading',
            'Desa Banjarsari',
            'Desa Boro',
            'Desa Ngreco',
            'Desa Ngrendeng',
            'Desa Olak-Alen',
            'Desa Pohgajih',
            'Desa Selorejo',
            'Desa Sidomulyo',
            'Desa Sumberagung',
        ],
        'Selopuro' => [
            'Desa Jambewangi',
            'Desa Jatitengah',
            'Desa Mandesan',
            'Desa Mronjo',
            'Desa Ploso',
            'Desa Popoh',
            'Desa Selopuro',
            'Desa Tegalrejo',
        ],
        'Srengat' => [
            'Desa Bangelenan',
            'Desa Dermojayan',
            'Desa Kandangan',
            'Desa Karanggayam',
            'Desa Kendalrejo',
            'Desa Kerjen',
            'Desa Maron',
            'Desa Ngaglik',
            'Desa Pakisrejo',
            'Desa Purwokerto',
            'Desa Selokajang',
            'Desa Wonorejo',
            'Kelurahan Dandong',
            'Kelurahan Kauman',
            'Kelurahan Srengat',
            'Kelurahan Togogan',
        ],
        'Sutojayan' => [
            'Desa Bacem',
            'Desa Kaulon',
            'Desa Pandanarum',
            'Desa Sumberjo',
            'Kelurahan Jegu',
            'Kelurahan Jingglong',
            'Kelurahan Kalipang',
            'Kelurahan Kedungbunder',
            'Kelurahan Kembangarum',
            'Kelurahan Sukorejo',
            'Kelurahan Sutojayan',
        ],
        'Talun' => [
            'Desa Bendosewu',
            'Desa Duren',
            'Desa Jabung',
            'Desa Jajar',
            'Desa Jeblog',
            'Desa Kendalrejo',
            'Desa Pasirharjo',
            'Desa Sragi',
            'Desa Tumpang',
            'Desa Wonorejo',
            'Kelurahan Bajang',
            'Kelurahan Kamulan',
            'Kelurahan Kaweron',
            'Kelurahan Talun',
        ],
        'Udanawu' => [
            'Desa Bakung',
            'Desa Bendorejo',
            'Desa Besuki',
            'Desa Jati',
            'Desa Karanggondang',
            'Desa Mangunan',
            'Desa Ringinanom',
            'Desa Slemanan',
            'Desa Sukorejo',
            'Desa Sumbersari',
            'Desa Temenggungan',
            'Desa Tunjung',
        ],
        'Wates' => [
            'Desa Mojorejo',
            'Desa Purworejo',
            'Desa Ringinrejo',
            'Desa Sukorejo',
            'Desa Sumberarum',
            'Desa Tugurejo',
            'Desa Tulungrejo',
            'Desa Wates',
        ],
        'Wlingi' => [
            'Desa Balerejo',
            'Desa Ngadirenggo',
            'Desa Tegalasri',
            'Desa Tembalang',
            'Kelurahan Babadan',
            'Kelurahan Beru',
            'Kelurahan Klemunan',
            'Kelurahan Tangkil',
            'Kelurahan Wlingi',
        ],
        'Wonodadi' => [
            'Desa Gandekan',
            'Desa Jaten',
            'Desa Kaliboto',
            'Desa Kebonagung',
            'Desa Kolomayan',
            'Desa Kunir',
            'Desa Pikatan',
            'Desa Rejosari',
            'Desa Salam',
            'Desa Tawangrejo',
            'Desa Wonodadi',
        ],
        'Wonotirto' => [
            'Desa Gununggede',
            'Desa Kaligrenjeng',
            'Desa Ngadipuro',
            'Desa Ngeni',
            'Desa Pasiraman',
            'Desa Sumberboto',
            'Desa Tambakrejo',
            'Desa Wonotirto',
        ],
    ]
];
